site_name: Volatus User Guide
docs_dir: 'src'
site_dir: 'docs'
strict: true
theme:
  name: material
  logo: volatus-user-guide/img/volatus.png
  favicon: volatus-user-guide/img/volatus.png
extra_css:
  - volatus-user-guide/volatus.css
plugins:
  - monorepo

nav:
  - Overview: 'index.md'
  - Volatus: '!include user_docs_content/mkdocs.yml'
